apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: house-price-api-monitor
  namespace: default
spec:
  selector:
    matchLabels:
      app: house-price-api
  endpoints:
  - port: http
    path: /metrics
    interval: 30s
